// Seslendirme metni (görev dosyası §12) ve her cümlenin filmdeki başlangıcı (saniye). Kurgu ve altyazı buradan
// okunur: tek kaynak. tempo: rubberband ile hız (1 = TTS'in doğal hızı); marka cümleleri bilerek yavaştır.
export const VOICE = [
  { id: 'v01', at: 0.9, text: 'Bir şantiyede gün, hiçbir zaman tek yerden başlamaz.' },
  { id: 'v02', at: 4.9, text: 'Mesajlar başka yerde.' },
  { id: 'v03', at: 6.7, text: 'Yoklama başka yerde.' },
  { id: 'v04', at: 8.35, text: 'Malzeme başka yerde.' },
  { id: 'v05', at: 10.05, text: 'Yapılan iş başka yerde.' },
  { id: 'v06', at: 12.05, text: 'Ve sonunda herkes aynı soruyu sorar:' },
  { id: 'v07', at: 14.95, text: 'Şu an ne durumdayız?', tempo: 0.86 },
  { id: 'v08', at: 17.05, text: 'İnşaat zaten karmaşık.', tempo: 0.8 },
  { id: 'v09', at: 19.55, text: 'Yönetimi olmak zorunda değil.', tempo: 0.82 },
  { id: 'v10', at: 22.25, text: 'İskele ERP.', tempo: 0.78 },
  { id: 'v11', at: 24.75, text: 'Firmanızı anlatın, paketinizi seçin.' },
  { id: 'v12', at: 27.95, text: 'Başvurunuz onaylandığında, size özel kurulum bağlantısıyla,' },
  { id: 'v13', at: 32.75, text: 'firma bilgilerinizi, patron hesabınızı ve ilk şantiyenizi birkaç adımda oluşturun.' },
  { id: 'v14', at: 38.75, text: 'Artık her şantiye, kendi çalışma alanında.' },
  { id: 'v15', at: 42.3, text: 'Fotoğraflar, videolar, sesli notlar ve günlük saha gelişmeleri, ait olduğu yerde kalır.' },
  { id: 'v16', at: 51.4, text: 'Şef yoklamayı sahada alır.' },
  { id: 'v17', at: 56.7, text: 'Ofis, aylık puantajı aynı kayıtlardan görür.' },
  { id: 'v18', at: 60.55, text: 'Gerektiğinde Excel’e aktarır.' },
  { id: 'v19', at: 63.4, text: 'Depodan ne çıktı, hangi şantiyeye gitti, ne iade edildi, ne geri bekleniyor…' },
  { id: 'v20', at: 71.2, text: 'Malzeme hareketleri, tek kayıtta.' },
  { id: 'v21', at: 74.9, text: 'İmalatta yapılan işi, kalan işi ve ilerlemeyi görün.' },
  { id: 'v22', at: 80.4, text: 'Taşeronların durumunu tahminle değil, kayıtla takip edin.' },
  { id: 'v23', at: 85.4, text: 'Görevi oluşturun.' },
  { id: 'v24', at: 86.85, text: 'Sorumlusunu ve teslim tarihini belirleyin.' },
  { id: 'v25', at: 90.4, text: 'İşin ne durumda olduğunu, tek bakışta görün.' },
  { id: 'v26', at: 94.2, text: 'Saha telefondan günceller.' },
  { id: 'v27', at: 96.45, text: 'Depo, hareketi kaydeder.' },
  { id: 'v28', at: 98.7, text: 'Ofis, bilgisayardan bütünü takip eder.' },
  { id: 'v29', at: 102.05, text: 'Herkes rolü kadar görür; herkes aynı işin içinde kalır.' },
  { id: 'v30', at: 106.75, text: 'Şantiyeler farklı olabilir. Ekipler farklı olabilir.' },
  { id: 'v31', at: 111.0, text: 'Ama kontrol, tek yerde olabilir.' },
  { id: 'v32', at: 113.95, text: 'İskele ERP.', tempo: 0.78 },
  { id: 'v33', at: 116.4, text: 'Saha hareketli. Kontrol sizde.', tempo: 0.84 },
]
